# coding: utf-8

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Fri Nov  2 10:28:04 2012
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui
from CVWeb import CVWeb

class Ui_mainWindow(object):
    def setupUi(self, main_window, cv):
        main_window.setObjectName("main_window")
        size_policy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(main_window.sizePolicy().hasHeightForWidth())
        main_window.setSizePolicy(size_policy)
        main_window.setMinimumSize(QtCore.QSize(1000, 631))
        main_window.setMaximumSize(QtCore.QSize(1000, 631))
        self.central_widget = QtGui.QWidget(main_window)
        size_policy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.central_widget.sizePolicy().hasHeightForWidth())
        self.central_widget.setSizePolicy(size_policy)
        self.central_widget.setMinimumSize(QtCore.QSize(1000, 631))
        self.central_widget.setMaximumSize(QtCore.QSize(1000, 631))
        self.central_widget.setObjectName("centralwidget")
        self.horizontal_layout_widget = QtGui.QWidget(self.central_widget)
        self.horizontal_layout_widget.setGeometry(QtCore.QRect(-1, -1, 992, 672))
        self.horizontal_layout_widget.setObjectName("horizontal_layout_widget")
        self.horizontal_layout = QtGui.QHBoxLayout(self.horizontal_layout_widget)
        self.horizontal_layout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontal_layout.setContentsMargins(0, 0, 0, 0)
        self.horizontal_layout.setObjectName("horizontal_layout")
        self.web_view = CVWeb(self.horizontal_layout_widget, cv)
        size_policy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.web_view.sizePolicy().hasHeightForWidth())
        self.web_view.setSizePolicy(size_policy)
        self.web_view.setMinimumSize(QtCore.QSize(600, 631))
        self.web_view.setMaximumSize(QtCore.QSize(600, 631))
        self.web_view.setObjectName("web_view")
        self.horizontal_layout.addWidget(self.web_view)
        self.vertical_layout = QtGui.QVBoxLayout()
        self.vertical_layout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.vertical_layout.setObjectName("vertical_layout")
        self.group_box = QtGui.QGroupBox(self.horizontal_layout_widget)
        self.group_box.setMinimumSize(QtCore.QSize(378, 200))
        self.group_box.setMaximumSize(QtCore.QSize(378, 200))
        self.group_box.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.group_box.setObjectName("group_box")
        self.start_button = QtGui.QPushButton(self.group_box)
        self.start_button.setEnabled(False)
        self.start_button.setGeometry(QtCore.QRect(90, 30, 90, 32))
        self.start_button.setObjectName("start_button")
        self.stop_button = QtGui.QPushButton(self.group_box)
        self.stop_button.setEnabled(False)
        self.stop_button.setGeometry(QtCore.QRect(190, 30, 90, 32))
        self.stop_button.setObjectName("stop_button")
        self.vertical_layout.addWidget(self.group_box)
        self.tab_widget = QtGui.QTabWidget(self.horizontal_layout_widget)
        self.tab_widget.setMinimumSize(QtCore.QSize(378, 411))
        self.tab_widget.setMaximumSize(QtCore.QSize(378, 411))
        self.tab_widget.setObjectName("tab_widget")
        self.tree_tab = QtGui.QWidget()
        self.tree_tab.setObjectName("tree_tab")
        self.tree_widget = QtGui.QTreeWidget(self.tree_tab)
        self.tree_widget.setGeometry(QtCore.QRect(0, 0, 372, 381))
        self.tree_widget.setMinimumSize(QtCore.QSize(372, 381))
        self.tree_widget.setMaximumSize(QtCore.QSize(372, 381))
        self.tree_widget.setFrameShape(QtGui.QFrame.Box)
        self.tree_widget.setHeaderHidden(False)
        self.tree_widget.setSortingEnabled(True)
        self.tree_widget.setColumnCount(2)
        self.tree_widget.setObjectName("tree_widget")
        self.tree_widget.headerItem().setText(0, "Key")
        self.tree_widget.headerItem().setText(1, "Value")
        self.tree_widget.setIndentation(10)
        self.tab_widget.addTab(self.tree_tab, "")
        self.log_tab = QtGui.QWidget()
        self.log_tab.setObjectName("log_tab")
        self.text_browser = QtGui.QTextBrowser(self.log_tab)
        self.text_browser.setGeometry(QtCore.QRect(0, 0, 372, 381))
        size_policy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.text_browser.sizePolicy().hasHeightForWidth())
        self.text_browser.setSizePolicy(size_policy)
        self.text_browser.setMinimumSize(QtCore.QSize(372, 381))
        self.text_browser.setMaximumSize(QtCore.QSize(372, 381))
        self.text_browser.setFrameShape(QtGui.QFrame.Box)
        self.text_browser.setFrameShadow(QtGui.QFrame.Sunken)
        self.text_browser.setAcceptRichText(True)
        self.text_browser.setObjectName("text_browser")
        self.tab_widget.addTab(self.log_tab, "")
        self.vertical_layout.addWidget(self.tab_widget)
        self.horizontal_layout.addLayout(self.vertical_layout)
        main_window.setCentralWidget(self.central_widget)

        self.retranslateUi(main_window)
        self.tab_widget.setCurrentIndex(1)
        QtCore.QObject.connect(self.start_button, QtCore.SIGNAL("clicked(bool)"), cv.run)
        QtCore.QObject.connect(self.stop_button, QtCore.SIGNAL("clicked(bool)"), cv.stop)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        main_window.setWindowTitle(QtGui.QApplication.translate("main_window", "AutoCV", None, QtGui.QApplication.UnicodeUTF8))
        self.group_box.setTitle(QtGui.QApplication.translate("main_window", "Bot Control", None, QtGui.QApplication.UnicodeUTF8))
        self.start_button.setText(QtGui.QApplication.translate("main_window", "Start Bot", None, QtGui.QApplication.UnicodeUTF8))
        self.stop_button.setText(QtGui.QApplication.translate("main_window", "Stop Bot", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tree_tab), QtGui.QApplication.translate("main_window", "Data Tree", None, QtGui.QApplication.UnicodeUTF8))
        self.text_browser.setHtml(QtGui.QApplication.translate("main_window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Bot information will be displayed here.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.log_tab), QtGui.QApplication.translate("main_window", "Log", None, QtGui.QApplication.UnicodeUTF8))